[package]
name = "crazy_jacks_crab_shack"
version = "0.1.0"
edition = "2024"

[dependencies]
console_error_panic_hook = "0.1.7"
leptos = { version = "0.7.7", features = ["csr"] }

[dependencies.web-sys]
version = "0.3"
features = ["DomRect"]